#!/bin/bash

export TZ=Europe/Paris

# qwerty
setxkbmap us

xset +fp /usr/share/fonts/efont/
xset fp rehash

/home/tjoly/ledger/conf/statusbar.sh &

xmodmap -e "keysym Alt_R = Mode_switch Mode_switch Mode_switch Mode_switch"
xmodmap ~/.xmodmaprc

emacs -bg-daemon

exec ssh-agent dwm
