#!/bin/bash

export TZ=Europe/Paris

# qwerty
setxkbmap us

xset +fp /usr/share/fonts/efont/
xset fp rehash

while :
do
    # Battery %
    per_bat=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | \
                     grep percentage | sed "s/[^0-9]*\([0-9]*\).*/\1/")

    # + date
   xsetroot -name "${per_bat}% | `date +\"%a %d %Y - %H:%M\"`"

    let count=61-`date +"%S"`
    sleep ${count}
done &

xmodmap -e "keysym Alt_R = Mode_switch Mode_switch Mode_switch Mode_switch"
xmodmap ~/.xmodmaprc

exec ssh-agent dwm
