#!/bin/bash

export TZ=Europe/Paris

# qwerty
setxkbmap us

xset +fp /usr/share/fonts/efont/
xset fp rehash

while :
do
    # Battery %
    per_bat=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | \
                     grep percentage | sed "s/[^0-9]*\([0-9]*\).*/\1/")

    # Volume %
    per_vol=$(z_volume get)

    # Gamma
    gamma=$(z_gamma get)

    # + date
    xsetroot -name "gamma: ${gamma} | vol: ${per_vol}% | bat: ${per_bat}% | `date +\"%a %d %Y - %H:%M\"`"

    let count=60-`date +"%S"`
    sleep ${count}
done &

xmodmap -e "keysym Alt_R = Mode_switch Mode_switch Mode_switch Mode_switch"
xmodmap ~/.xmodmaprc

emacs -bg-daemon

xrandr --listactivemonitors | grep -q HDMI-1
HDMI1=$?
xrandr --listactivemonitors | grep -q DP-3
DP3=$?

if [ ${HDMI1} -eq 0 ]; then
    if [ ${DP3} -eq 0 ]; then
        .screenlayout/ledger.sh
    else
        .sceenlayout/home.sh
    fi
fi

exec ssh-agent dwm
