export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="af-magic"

plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    web-search
    history
    colored-man-pages
)

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='emacs'
else
  export EDITOR='emacs'
fi

# Aliases
alias emacs_c="emacsclient --create-frame"
alias e="emacs --no-init-file -l ~/git/conf/emacs.d/emacs.el"

# Ctrl -> <-
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word
bindkey '^H' backward-kill-word
bindkey '^[[3^' kill-word
bindkey '^[[7~' beginning-of-line
bindkey '^[[8~' end-of-line

# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export PATH="$HOME/.local/bin:$PATH" # pip binaries

# Tells 'less' not to paginate if less than a page
export LESS="-F -X $LESS"

# ledger
source $HOME/git/ledger-utils/ledgerrc.sh
source $HOME/git/conf/session_init/session_init.sh

# autocompletion
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#ffffff,bg=cyan,bold,underline"
