#!/usr/bin/env bash

regexp=(
    "#*"
    "*.gcda"
    ".#*"
    "__pycache__"
)

for r in ${regexp[*]}
do
    echo "====> clean $r"
    for f in $(find . -name "$r")
    do
        echo " + $f: deleted"
        rm -rf $f
    done
done
